---
sidebar: sidebar 
permalink: reference-new.html 
keywords: new, new features, features, release notes, enhancements 
summary: Cloud Volumes ONTAP 9.12.0 inclut une nouvelle amélioration. 
---
= Nouveautés d'Cloud Volumes ONTAP 9.12.0
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.12.0 inclut une nouvelle amélioration.

D'autres fonctionnalités et améliorations sont également introduites dans les dernières versions de BlueXP. Voir https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Notes de mise à jour BlueXP"^] pour plus de détails.



== 9.12.0 P1 (15 décembre 2022)

Cloud Volumes ONTAP 9.12.0 P1 est désormais disponible dans AWS et Google Cloud. Cette version inclut la nouvelle fonction suivante.



=== Prise en charge de m6id.32xlarge dans AWS

Cloud Volumes ONTAP est désormais pris en charge avec le type d'instance EC2 m6id.32xlarge dans AWS.

Pour plus d'informations, consultez lelink:reference-configs-aws.html["configurations prises en charge"].



== Notes de mise à niveau

Lisez ces notes pour en savoir plus sur la mise à niveau vers cette version.



=== Comment mettre à niveau

Les mises à niveau de Cloud Volumes ONTAP doivent être effectuées depuis BlueXP. Vous ne devez pas mettre à niveau Cloud Volumes ONTAP à l'aide de System Manager ou de l'interface de ligne de commandes. Cela peut affecter la stabilité du système.

http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["Découvrez comment effectuer la mise à niveau lorsque BlueXP vous avertit"^].



=== Chemin de mise à niveau pris en charge

Vous pouvez effectuer une mise à niveau vers Cloud Volumes ONTAP 9.12.0 à partir de la version 9.11.1. BlueXP vous invitera à mettre à niveau les systèmes Cloud Volumes ONTAP éligibles vers cette version.



=== Version requise du connecteur

BlueXP  Connector doit exécuter la version 3.9.24 ou ultérieure pour déployer de nouveaux systèmes Cloud Volumes ONTAP 9.12.0 et mettre à niveau les systèmes existants vers cette version.


TIP: Les mises à niveau automatiques du connecteur sont activées par défaut, vous devez donc exécuter la dernière version.



=== Ou non

* La mise à niveau d'un système à un nœud unique permet de mettre le système hors ligne pendant 25 minutes au cours desquelles les E/S sont interrompues.
* La mise à niveau d'une paire haute disponibilité s'effectue sans interruption et les E/S sont continues. Au cours de ce processus de mise à niveau sans interruption, chaque nœud est mis à niveau en tandem afin de continuer à traiter les E/S aux clients.




=== Mises à niveau dans AWS avec les types d'instances EC2 c4, m4 et r4

Dans AWS, les types d'instances EC2 c4, m4 et r4 ne sont plus pris en charge par les nouveaux déploiements Cloud Volumes ONTAP. Si un système existant s'exécute sur un type d'instance c4, m4 ou r4, vous devez passer à un type d'instance dans la famille d'instances c5, m5 ou r5. Si vous ne pouvez pas modifier le type d'instance, vous devez activer la mise en réseau améliorée avant de procéder à la mise à niveau.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrades-in-aws-with-c4-m4-and-r4-ec2-instance-types["Découvrez comment effectuer une mise à niveau dans AWS avec les types d'instances EC2 c4, m4 et r4"^]. link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Découvrez comment modifier le type d'instance EC2 pour Cloud Volumes ONTAP"^].

Reportez-vous link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Support NetApp"^]à pour en savoir plus sur la fin de disponibilité et la prise en charge de ces types d'instances.
